#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times

args=("$@")
if [ "$#" == 1 ]
then
	ping -c 5 "${args[0]}" 
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
